name: flutter_final
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_core: 2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  logger: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.1.0
  carousel_slider: ^4.2.1
  swipe_cards: ^2.0.0+1
  flip_card: ^0.7.0
  image_picker: ^1.0.8
  flutter_tts: ^4.0.2
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  collection: ^1.18.0
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  universal_html: ^2.2.4
  shared_preferences: ^2.2.3
  http: ^1.2.0
  path: ^1.8.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  intl: ^0.18.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "icon/icon.png"
  web:
    generate: true
    image_path: "icon/icon.png"
    background_color: "#3D3D3D"
    theme_color: "#3D3D3D"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
